/* ───────────────────────────────────────────────────────────
   middleware.js — Vercel Edge Middleware for OG social previews
   Hubbell Civil War Letters Project

   Intercepts bot/crawler requests, reads query params, and
   injects dynamic <meta> tags for rich link previews in
   Slack, Discord, Twitter/X, Facebook, iMessage, WhatsApp,
   Telegram, Bluesky, Mastodon, Signal, LinkedIn, Pinterest.
   Real users get the unmodified page.

   Preview cards live in /og :
     card-<slug>.jpg  1200x630 static (all platforms)
     anim-<slug>.gif   960x504 looping (platforms that animate)
   Cards are generated by scripts/og/build_og_cards.py.
   ─────────────────────────────────────────────────────────── */

let _ogDataCache = null;

async function getOgData(origin) {
  if (_ogDataCache) return _ogDataCache;
  try {
    const res = await fetch(origin + '/_og-data.json');
    if (res.ok) _ogDataCache = await res.json();
  } catch (e) { /* fallback to empty */ }
  return _ogDataCache || {};
}

export const config = {
  matcher: [
    '/',
    '/index',
    '/experience-v2/landing',
    '/hubbell-dashboard',
    '/search',
    '/reader',
    '/brother-henry',
    '/brother-alexander',
    '/brother-james',
    '/brother-charles',
    '/mother-frances',
    '/who-they-were',
    '/viz-emotional-arcs',
    '/viz-emotional-arcs-v2',
    '/viz-map-fullwar',
    '/viz-map-moves',
    '/viz-health-ledger',
    '/viz-money-story',
    '/viz-people-web',
    '/viz-what-they-didnt-know',
    '/viz-what-they-wrote-about',
    '/viz-mothers-war',
    '/the-collection',
    '/the-unguarded-letter',
    '/their-own-words',
    '/about',
    '/faq',
    '/press',
  ],
};

// Social crawlers that need OG tags injected
const BOT_PATTERN = /Slackbot|Twitterbot|facebookexternalhit|LinkedInBot|Discordbot|WhatsApp|Applebot|TelegramBot|Googlebot|bingbot|Pinterest|redditbot|SkypeUriPreview|Iframely|Embedly|Mastodon|Bluesky|bsky|cardyb|Signal|vkShare|Snapchat|Line\/|DuckDuckBot|SummalyBot/i;

// Platforms whose link cards actually play animated GIF og:images
const ANIMATED_PATTERN = /Discordbot|TelegramBot|Slackbot/i;

const SITE_NAME = 'Hubbell Civil War Letters';
const DEFAULT_DESC = '273 letters from four brothers and their mother, 1861–1870 — an interactive exploration of the American Civil War through one family\'s words.';

// Page-specific default titles
const PAGE_TITLES = {
  '/': 'The Hubbell Brothers — Civil War Letters, 1861–1870',
  '/index': 'Hubbell Civil War Letters',
  '/experience-v2/landing': 'The Hubbell Brothers — Civil War Letters, 1861–1870',
  '/hubbell-dashboard': 'Parallel Lives — Hubbell Civil War Letters',
  '/search': 'Search — Hubbell Civil War Letters',
  '/reader': 'The Letter Reader — Hubbell Civil War Letters',
  '/brother-henry': 'Henry Hubbell — 34th NY Infantry',
  '/brother-alexander': 'Alexander F. Hubbell — 60th NY Infantry',
  '/brother-james': 'James Hubbell — 16th NY Heavy Artillery',
  '/brother-charles': 'Charles F. Hubbell — Home Front',
  '/mother-frances': 'Frances Hubbell — A Mother\'s War',
  '/who-they-were': 'Who They Were — The Hubbell Family',
  '/viz-emotional-arcs': 'Emotional Arcs — Civil War Letters',
  '/viz-emotional-arcs-v2': 'Emotional Arcs — Civil War Letters',
  '/viz-map-fullwar': 'A Map That Moves — Following the Hubbells',
  '/viz-map-moves': 'A Map That Moves — Following the Hubbells',
  '/viz-health-ledger': 'The Wellness Ledger — Physical Well-Being in the Civil War',
  '/viz-money-story': 'The Money Story — Wartime Finances',
  '/viz-people-web': 'The People Web — Connections Across 273 Letters',
  '/viz-what-they-didnt-know': 'What They Didn\'t Know — Dramatic Irony',
  '/viz-what-they-wrote-about': 'What They Wrote About — Topic Landscape',
  '/viz-mothers-war': 'A Mother\'s War — Frances Hubbell',
  '/the-collection': 'The Archive — Five Generations of Stewardship',
  '/the-unguarded-letter': 'The Unguarded Letter',
  '/their-own-words': 'In Their Own Words — 50 Questions Answered from the Letters',
  '/about': 'About — Hubbell Civil War Letters',
  '/faq': 'FAQ — Hubbell Civil War Letters',
  '/press': 'Press Kit — Hubbell Civil War Letters',
};

// pathname → /og card slug (card-<slug>.jpg, optionally anim-<slug>.gif)
const PAGE_CARDS = {
  '/': 'home',
  '/index': 'default',
  '/experience-v2/landing': 'home',
  '/hubbell-dashboard': 'parallel-lives',
  '/search': 'search',
  '/reader': 'reader',
  '/brother-henry': 'henry',
  '/brother-alexander': 'alexander',
  '/brother-james': 'james',
  '/brother-charles': 'charles',
  '/mother-frances': 'frances',
  '/who-they-were': 'who-they-were',
  '/viz-emotional-arcs': 'emotional-arcs',
  '/viz-emotional-arcs-v2': 'emotional-arcs',
  '/viz-map-fullwar': 'map',
  '/viz-map-moves': 'map',
  '/viz-health-ledger': 'health-ledger',
  '/viz-money-story': 'money-story',
  '/viz-people-web': 'people-web',
  '/viz-what-they-didnt-know': 'what-they-didnt-know',
  '/viz-what-they-wrote-about': 'what-they-wrote-about',
  '/viz-mothers-war': 'frances',
  '/the-collection': 'collection',
  '/the-unguarded-letter': 'unguarded-letter',
  '/their-own-words': 'their-own-words',
  '/about': 'about',
  '/faq': 'faq',
  '/press': 'press',
};

// Card slugs that also have an animated variant (anim-<slug>.gif)
const ANIMATED_CARDS = new Set([
  'home', 'parallel-lives', 'map', 'health-ledger', 'people-web', 'money-story',
  'henry', 'alexander', 'james', 'charles', 'frances',
  'letter-henry', 'letter-alexander', 'letter-james', 'letter-charles', 'letter-mother',
]);

const PERSON_CARDS = { henry: 'henry', alexander: 'alexander', james: 'james', charles: 'charles', mother: 'frances', frances: 'frances' };

const MONTH_NAMES = [
  '', 'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'
];

function formatDate(dateStr) {
  if (!dateStr) return '';
  const parts = dateStr.split('-');
  if (parts.length < 3) return dateStr;
  const month = MONTH_NAMES[parseInt(parts[1])] || parts[1];
  return `${month} ${parseInt(parts[2])}, ${parts[0]}`;
}

function generateOgMeta(pathname, params, ogData) {
  let title = PAGE_TITLES[pathname] || SITE_NAME;
  let description = DEFAULT_DESC;
  let card = PAGE_CARDS[pathname] || 'default';

  const letterId = params.get('letter');
  const personParam = params.get('person');
  const linkParam = params.get('link');
  const queryParam = params.get('q');
  const brotherParam = params.get('brother');
  const dateParam = params.get('date');
  const eventParam = params.get('event');

  // Letter-specific preview (works on any page)
  if (letterId && ogData[letterId]) {
    const l = ogData[letterId];
    title = `Letter from ${l.an}, ${formatDate(l.d)}`;
    description = l.loc ? `Written from ${l.loc}` : '';
    if (l.ex) {
      description += description ? ' — ' : '';
      description += `"${l.ex}"`;
    }
    if (l.r) {
      description += ` (to ${l.r})`;
    }
    if (l.a && PERSON_CARDS[l.a]) card = 'letter-' + (l.a === 'frances' ? 'mother' : l.a);
  }

  // Who They Were: specific family member
  else if (personParam && pathname === '/who-they-were' && PERSON_CARDS[personParam.toLowerCase()]) {
    const p = personParam.toLowerCase();
    const names = { henry: 'Henry Hubbell', alexander: 'Alexander F. Hubbell', james: 'James Hubbell', charles: 'Charles F. Hubbell', mother: 'Frances Hubbell', frances: 'Frances Hubbell' };
    title = `${names[p]} — Who They Were`;
    description = `${names[p]}'s life and war, told through the family letters.`;
    card = PERSON_CARDS[p];
  }

  // People Web: linked pair
  else if (linkParam && pathname === '/viz-people-web') {
    const names = linkParam.split(',').map(n => n.trim());
    if (names.length === 2) {
      title = `${names[0]} & ${names[1]} — Connected`;
      description = `Explore the relationship between ${names[0]} and ${names[1]} across the Hubbell Civil War letters.`;
    }
  }

  // People Web: single person
  else if (personParam && pathname === '/viz-people-web') {
    title = `${personParam} — People Web`;
    description = `${personParam} in the Hubbell Civil War letter network — connections, mentions, and shared letters.`;
    const p = personParam.toLowerCase();
    if (PERSON_CARDS[p]) card = PERSON_CARDS[p];
  }

  // Search query
  else if (queryParam && pathname === '/search') {
    title = `Search: ${queryParam} — ${SITE_NAME}`;
    description = `Search results for "${queryParam}" across 273 Civil War letters from the Hubbell family.`;
  }

  // Map: brother + date
  else if (pathname === '/viz-map-fullwar' || pathname === '/viz-map-moves') {
    const brotherNames = { henry: 'Henry Hubbell', alexander: 'Alexander F. Hubbell', james: 'James Hubbell', charles: 'Charles F. Hubbell' };
    if (brotherParam && dateParam) {
      const name = brotherNames[brotherParam] || brotherParam;
      title = `${name} — ${formatDate(dateParam)}`;
      description = `Follow ${name}'s Civil War journey on ${formatDate(dateParam)}.`;
    } else if (brotherParam) {
      title = `Following ${brotherNames[brotherParam] || brotherParam}`;
      description = `Track ${brotherNames[brotherParam] || brotherParam}'s movements through the Civil War.`;
    } else if (dateParam) {
      title = `The War on ${formatDate(dateParam)}`;
      description = `Where were the Hubbell brothers on ${formatDate(dateParam)}?`;
    }
    if (brotherParam && PERSON_CARDS[brotherParam]) card = PERSON_CARDS[brotherParam];
  }

  // What They Didn't Know: event index
  else if (eventParam && pathname === '/viz-what-they-didnt-know') {
    title = `Dramatic Irony #${parseInt(eventParam) + 1} — What They Didn't Know`;
    description = `Explore moments of dramatic irony in the Hubbell Civil War letters — what the brothers wrote vs. what was really happening.`;
  }

  return { title, description, card };
}

export default async function middleware(request) {
  const userAgent = request.headers.get('user-agent') || '';

  // Only modify response for known bots
  if (!BOT_PATTERN.test(userAgent)) {
    return; // Pass through unmodified
  }

  const url = new URL(request.url);

  // Load OG data and generate meta
  const ogData = await getOgData(url.origin);
  const { title, description, card } = generateOgMeta(url.pathname, url.searchParams, ogData);

  // Fetch the original response
  const response = await fetch(request);
  const contentType = response.headers.get('content-type') || '';

  // Only modify HTML responses
  if (!contentType.includes('text/html')) {
    return response;
  }

  const html = await response.text();

  // Pick the image: animated GIF for platforms that play it, static JPG otherwise
  const wantsAnimated = ANIMATED_PATTERN.test(userAgent) && ANIMATED_CARDS.has(card);
  const image = url.origin + (wantsAnimated ? `/og/anim-${card}.gif` : `/og/card-${card}.jpg`);
  const imageDims = wantsAnimated
    ? '' // GIFs may be re-scaled below 960x504 for size budgets — omit dims
    : `    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
`;

  // Build OG meta tags
  const ogTags = `
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="${SITE_NAME}">
    <meta property="og:title" content="${escapeHtml(title)}">
    <meta property="og:description" content="${escapeHtml(description)}">
    <meta property="og:image" content="${image}">
    <meta property="og:image:type" content="${wantsAnimated ? 'image/gif' : 'image/jpeg'}">
${imageDims}    <meta property="og:image:alt" content="${escapeHtml(title)}">
    <meta property="og:url" content="${escapeHtml(url.toString())}">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="${escapeHtml(title)}">
    <meta name="twitter:description" content="${escapeHtml(description)}">
    <meta name="twitter:image" content="${url.origin}/og/card-${card}.jpg">
  `;

  // Drop any static baseline og/twitter tags, then inject the computed set
  const stripped = html.replace(/[ \t]*<meta (?:property|name)="(?:og:|twitter:)[^"]*"[^>]*>\s*\n?/g, '')
                       .replace(/[ \t]*<!-- og:(?:begin|end) -->\s*\n?/g, '');
  const modifiedHtml = stripped.replace('</head>', ogTags + '\n</head>');

  const headers = new Headers(response.headers);
  headers.set('content-type', 'text/html; charset=utf-8');

  return new Response(modifiedHtml, {
    status: response.status,
    headers,
  });
}

function escapeHtml(str) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}
