# -*- coding: utf-8 -*-
"""Their Own Words v2 content — Act I second-cell fills (body/purse/family)."""

ACT_1_FILL = [

dict(qid='a1-body-2', act=1, theme='body', source=('gap', 'I-body', 2), recip='to his mother', date_str='December 16, 1861',
  stem='Sick in his first army winter, Alexander is nursed with toast and tea — by his captain. What does this scene reveal about Civil War medical care in 1861?',
  choices=['Officers were required by regulation to nurse their men', 'There was hardly any system yet — care of the sick ran on improvisation, comrades, and kind officers', 'The army’s nurse corps handled all camp illness', 'Sick soldiers were routinely sent home to recover'],
  answer=1,
  whyRight="That's the truth of it. In 1861 the army had no general hospitals worth the name, no ambulance corps, no trained nurses in the camps — a sick private's care was whoever loved him nearest. Alexander drew a good captain.",
  whyWrong={'2': "The war eventually built exactly that — Dorothea Dix's nurses, the great pavilion hospitals — but in December 1861 almost none of it existed yet.",
            '3': "Furloughs for sickness were rare and begrudged — armies feared men who went home sick would stay home well."},
  expansion="The Union army entered the war with a Medical Bureau built for 16,000 frontier regulars — ancient surgeons, no general hospitals, no ambulance system, no nursing corps — and then camp disease hit armies of half a million. The first winter was the system's failure at full exposure: regimental hospitals were tents with straw, 'nursing' meant convalescents and bandsmen, and a sick soldier's real safety net was social — messmates, chaplains, officers like Captain Ransom who carried toast and tea. Reform came, driven by catastrophe and the Sanitary Commission's inspections: Letterman's ambulance corps in 1862, a purpose-built pavilion hospital network that grew to 200,000 beds, Dix's and eventually thousands of female nurses. By 1864 a sick soldier entered an actual system (Act IV shows Alexander riding one down a hospital railroad). In 1861 he entered a lottery of kindness — and this letter is a winning ticket, lovingly documented.",
  context="'Very, very, very, very kind' — four verys, from the family's most word-careful son; the gratitude is practically underlined through the page. The archive keeps this scene because Frances kept needing it: the Wellness Ledger's profile of Alexander opens with this exact December illness and this exact captain, because a Baltimore cold under Ransom's care is where the collection's whole medical story begins. There's a quiet class note worth hearing too — a captain personally carrying toast to a seventeen-year-old private was noteworthy enough to report, which tells you the norm it exceeded. The brothers' letters home run thick with officers judged precisely this way (the good colonel, the tyrant major): to the family reading in Champlain, an officer's kindness WAS the army's healthcare policy. In 1861, they were more right than wrong."),

dict(qid='a1-purse-2', act=1, theme='purse', source=('gap', 'I-purse', 0), recip='to his mother', date_str='July 6, 1861',
  stem='In the collection’s very first letter, Henry is already asking whether $8 made it home. What was this money?',
  choices=['His enlistment bounty, mailed the day he signed', 'Part of his soldier’s pay, sent home to the family farm — the correspondence’s financial engine from page one', 'Repayment of a debt to a neighbor', 'Money he won at cards in camp'],
  answer=1,
  whyRight="That's the truth of it. The first letter in the archive already runs the family's wartime economy: wages earned in camp, folded into an envelope, and anxiously tracked until Champlain confirmed receipt.",
  whyWrong={'0': "The $100 federal bounty was mostly paid at DISCHARGE, not enlistment — in July 1861 Henry had seen none of it.",
            '3': "Henry's letters show him dodging the camp's vices with a farm boy's thrift — and $8 was more than half a month's pay, not a card-table sum."},
  expansion="Follow the mechanics, because thousands of families ran on them: a private's $13 arrived (late) in camp, and some portion — commonly half or more — turned around by mail or express toward home, where it was farm labor the family had lost, in cash form. No allotment system yet existed to send pay home automatically (states and the army improvised them later), so the transfer ran on trust and the mails: cash folded in letters, sums entrusted to adjutants and express companies, and then the anxious audit loop Henry opens here — DID YOU GET IT? — that never closes for four years. Multiply this envelope by the Union's million soldiers and you get the war's least-studied logistics: a continuous, informal river of small remittances northward that kept soldier families solvent. The Hubbell archive documents one tributary of it with bookkeeping completeness: $8 in 1861 to $350 in 1865, every arrival confirmed by a mother's pen.",
  context="The archive's opening page, and the family's whole grammar is already present: arrival reported, regiment praised, spelling apologized for ('You must excuse bad spelling and improper grammar' — his own words, four sentences from this one), and the money tracked. One provenance note worth knowing as you read: Henry headed this letter 'June 6th, 1861,' but the archive dates it July 6 — the 34th New York didn't reach Washington until early July, and new soldiers misdated letters constantly; the project's editorial layer keeps both facts honestly separated. That's this whole site's method in one detail: the letter says what it says, the record says what it proves, and you get to see both. Eight dollars, faithfully worried over — the first ledger entry of a correspondence that ends, fifty questions from here, with a paymaster and a tea table."),

dict(qid='a1-family-2', act=1, theme='family', source=('gap', 'I-family', 0), recip='to his mother', date_str='July 6, 1861',
  stem='Henry priced a trip home at twelve dollars and decided it “would not pay.” What does this arithmetic tell you about a volunteer’s furlough?',
  choices=['Furloughs were free but limited to officers', 'Going home was possible but expensive — a visit could cost a month’s wages, and the soldier bore it', 'The army paid travel costs for family visits once a year', 'Leaving camp for any reason was desertion'],
  answer=1,
  whyRight="That's the truth of it. Twelve dollars against thirteen a month — Henry runs the numbers like the farmer's son he is, and the farm loses. Distance in 1861 was measured in wages as much as miles.",
  whyWrong={'3': "A furlough was legal leave, signed and dated — desertion was leaving without one. Henry is pricing the legal kind and finding it dear.",
            '2': "No such benefit existed at any point in the war — the government moved soldiers for war, not for homesickness."},
  expansion="The volunteer of 1861 signed away proximity: furloughs were discretionary, scarce (armies were being assembled, not dispersed), and traveled at the soldier's expense on civilian railroads — so a Champlain-to-Washington round trip genuinely could consume a month's pay. The result shaped the whole culture of the war: for most men, HOME became something that arrived by mail or not at all, visits so rare they were legendary events (the 1864 'veteran furlough' — thirty days, part of the reenlistment bounty package — was prized above the cash by many). Henry's twelve-dollar decision, multiplied across the armies, is why the Civil War became history's most-written war: the letter wasn't a supplement to presence; it was the entire relationship, priced into being by exactly this arithmetic. When this game's Act I mail question told you the letters were a lifeline, here is the invoice that made them one.",
  context="Look at the tension inside the sentence: 'I would have been VERY GLAD to have gone home' — the longing stated plainly, then dismantled by price, then the poignant coda in the same passage: had he known it could be done for five dollars, he would have gone. He never did. Henry had fourteen months left, all of them in uniform, none of them home; the twelve dollars he saved is one of those details that grief later reprices beyond any currency, and you can only read it knowing what he couldn't. That is this archive's particular power — the letters are innocent of their own endings. First letter, and the collection's deepest current is already running: a family measuring the distance between a farm and a war, in dollars, in pages, in mornings at the post office. Fifty questions from now it closes to the width of a tea table — for two of them."),
]
